version: "3.9"
services:
  train:
    image: cu110-pytorch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"
    volumes:
      - "./:/workspace/DiffRNAFold"
      - "../GSAE:/workspace/GSAE/"
      - "../RNABERT:/workspace/RNABERT/"
      - "E:/data:/data"
    working_dir: "/workspace/"
    entrypoint: /docker-entrypoint.sh